### ISSUE TITLE
Null Packet

### ISSUE THREAD

**Issue by I2pRandom** [iPortalTeam/ImmersivePortalsModForForge#157]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

No

### Forge Version

40.2.17

### ImmersivePortals Version

1.4.20

### Latest Log

https://gist.github.com/I2pRandom/85e451382564f768bd606da6144b2ea3

### Steps to Reproduce

Place mod on server, and attempt to join.

### What You Expected

Join server without null packet error

### What Happened Instead

Got null error. 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by I2pRandom** [comment]
I have just noticed this error does not seem to actually get output to the log or debug log when it occurs
Only showing up in my client, which is bizarre so i'm gonna go head and just directly post the error here. 

```
[15:41:17] [Render thread/ERROR] [minecraft/BlockableEventLoop]: Error executing task on Client
java.util.NoSuchElementException: packet_handler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[netty-all-4.1.68.Final.jar%2316!/:4.1.68.Final] {}
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248) ~[netty-all-4.1.68.Final.jar%2316!/:4.1.68.Final] {}
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[netty-all-4.1.68.Final.jar%2316!/:4.1.68.Final] {}
	at net.minecraftforge.network.filters.NetworkFilters.lambda$injectIfNecessary$1(NetworkFilters.java:34) ~[forge-1.18.2-40.2.17-universal.jar%23410!/:?] {re:classloading}
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:196) ~[guava-31.0.1-jre.jar%2318!/:?] {}
	at net.minecraftforge.network.filters.NetworkFilters.injectIfNecessary(NetworkFilters.java:30) ~[forge-1.18.2-40.2.17-universal.jar%23410!/:?] {re:classloading}
	at net.minecraftforge.network.NetworkHooks.sendMCRegistryPackets(NetworkHooks.java:108) ~[forge-1.18.2-40.2.17-universal.jar%23410!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:core.NetworkHooksMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5998_(ClientPacketListener.java:375) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_clientplaynethandler_cleanup,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_cleanup,xf:fml:xaerominimap:xaero_clientplaynethandler_handlejoingame,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlejoingame,xf:fml:xaerominimap:xaero_clientplaynethandler_handlemultiblockchange,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlemultiblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_updatelevelchunk,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_updatelevelchunk,xf:fml:xaerominimap:xaero_clientplaynethandler_queuelightupdate,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_queuelightupdate,xf:fml:xaerominimap:xaero_clientplaynethandler_handleblockchange,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handleblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handlespawnpoint,xf:fml:xaeroworldmap:xaero_clientplaynethandler_handlespawnpoint,xf:fml:openpartiesandclaims:xaero_pac_clientplaynethandler_handleinitializeborder,xf:fml:xaerominimap:xaero_clientplaynethandlerclass,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandlerclass,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_clientplaynethandler_cleanup,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_cleanup,xf:fml:xaerominimap:xaero_clientplaynethandler_handlejoingame,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlejoingame,xf:fml:xaerominimap:xaero_clientplaynethandler_handlemultiblockchange,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlemultiblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_updatelevelchunk,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_updatelevelchunk,xf:fml:xaerominimap:xaero_clientplaynethandler_queuelightupdate,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_queuelightupdate,xf:fml:xaerominimap:xaero_clientplaynethandler_handleblockchange,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handleblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handlespawnpoint,xf:fml:xaeroworldmap:xaero_clientplaynethandler_handlespawnpoint,xf:fml:openpartiesandclaims:xaero_pac_clientplaynethandler_handleinitializeborder,xf:fml:xaerominimap:xaero_clientplaynethandlerclass,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandlerclass,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.network.protocol.game.ClientboundLoginPacket.m_5797_(ClientboundLoginPacket.java:83) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?] {re:mixin,re:classloading}
	at net.minecraft.network.protocol.game.ClientboundLoginPacket.m_5797_(ClientboundLoginPacket.java:19) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?] {re:mixin,re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?] {re:mixin,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1015) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:APP:mixins.modernui-forge.json:MixinMinecraft,pl:mixin:APP:immediatelyfast.mixins.json:hud_batching.MixinMinecraftClient,pl:mixin:APP:neat.mixins.json:MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:embeddium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:tenshilib.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Images,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:chunkpregen.mixins.json:client.MinecraftMixin,pl:mixin:APP:cgm.mixins.json:client.MinecraftMixin,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:valkyrienskies-common.mixins.json:client.MixinMinecraft,pl:mixin:APP:embeddiumplus.mixin.json:dynlights.MinecraftMixin,pl:mixin:APP:embeddiumplus.mixin.json:frames.GpuUsageMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinMinecraftClient,pl:mixin:APP:quartz.mixins.json:MinecraftShutdownMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.codechickenlib.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:imm_ptl.mixins.json:client.MixinMinecraft,pl:mixin:APP:imm_ptl.mixins.json:client.block_manipulation.MixinMinecraft_B,pl:mixin:APP:imm_ptl.mixins.json:client.sync.MixinMinecraft_RedirectedPacket,pl:mixin:APP:puzzleslib.common.mixins.json:client.accessor.MinecraftAccessor,pl:mixin:APP:puzzleslib.forge.mixins.json:client.MinecraftForgeMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:assets/mining_dimension/mining_dimension.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:APP:mixins.modernui-forge.json:MixinMinecraft,pl:mixin:APP:immediatelyfast.mixins.json:hud_batching.MixinMinecraftClient,pl:mixin:APP:neat.mixins.json:MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:embeddium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:tenshilib.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Images,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:chunkpregen.mixins.json:client.MinecraftMixin,pl:mixin:APP:cgm.mixins.json:client.MinecraftMixin,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:valkyrienskies-common.mixins.json:client.MixinMinecraft,pl:mixin:APP:embeddiumplus.mixin.json:dynlights.MinecraftMixin,pl:mixin:APP:embeddiumplus.mixin.json:frames.GpuUsageMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinMinecraftClient,pl:mixin:APP:quartz.mixins.json:MinecraftShutdownMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.codechickenlib.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:imm_ptl.mixins.json:client.MixinMinecraft,pl:mixin:APP:imm_ptl.mixins.json:client.block_manipulation.MixinMinecraft_B,pl:mixin:APP:imm_ptl.mixins.json:client.sync.MixinMinecraft_RedirectedPacket,pl:mixin:APP:puzzleslib.common.mixins.json:client.accessor.MinecraftAccessor,pl:mixin:APP:puzzleslib.forge.mixins.json:client.MinecraftForgeMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:assets/mining_dimension/mining_dimension.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23405!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.17.jar%2352!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc2.jar:mmc2] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?] {}
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) [NewLaunch.jar:?] {}
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186) [NewLaunch.jar:?] {}
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?] {}
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?] {}
```
