### ISSUE TITLE
Mirrors don't work

### ISSUE THREAD

**Issue by Lolothepro** [iPortalTeam/ImmersivePortalsModForForge#16]
### According to your testing, does the issue occur with ONLY Immersive Portals mod?

Yes

### Forge Version

*****

### ImmersivePortals Version

1.4.9pre

### Latest Log

https://gist.github.com/Lolothepro/9fe98b73253b1df093de4841f84cc744

### Steps to Reproduce

Tried to make a mirror

### What You Expected

Mirrors are impossible to create.

### What Happened Instead

**

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
Please try to reproduce the issue on an up to date version.

**Comment by Lolothepro** [comment]
?

**Comment by Nick1st** [comment]
https://www.curseforge.com/minecraft/mc-mods/immersive-portals-for-forge/files/3964094

**Comment by Lolothepro** [comment]
> Please try to reproduce the issue on an up to date version.

```
[Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@3385582c, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.EntityType.m_20615_(net.minecraft.world.level.Level)" because "qouteall.imm_ptl.core.portal.BreakableMirror.entityType" is null
	at qouteall.imm_ptl.core.portal.BreakableMirror.createMirror(BreakableMirror.java:122) ~[immersive-portals-1.4.9-mc1.18.2-forge.jar%2360!/:1.4.9] {re:mixin,re:classloading}
	at net.minecraft.world.item.FlintAndSteelItem.handler$zfe000$onUseFlintAndSteel(FlintAndSteelItem.java:541) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?] {re:mixin,re:classloading,pl:mixin:APP:imm_ptl_peripheral.mixins.json:common.portal_generation.MixinFlintAndSteelItem,pl:mixin:A}
	at net.minecraft.world.item.FlintAndSteelItem.m_6225_(FlintAndSteelItem.java) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?] {re:mixin,re:classloading,pl:mixin:APP:imm_ptl_peripheral.mixins.json:common.portal_generation.MixinFlintAndSteelItem,pl:mixin:A}
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:601) ~[forge-1.18.2-40.1.76-universal.jar%2368!/:?] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:222) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:imm_ptl.mixins.json:common.portal_generation.MixinItemStack,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:354) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?] {re:computing_frames,re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:985) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:30) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:762) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2363!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
```
it also happens
