### ISSUE TITLE
[Crash] Krypton / Pluto

### ISSUE THREAD

**Issue by Shadowex3** [iPortalTeam/ImmersivePortalsModForForge#18]
### According to your testing, does the issue occur with ONLY Immersive Portals mod?

No

### Forge Version

40.1.73

### ImmersivePortals Version

1.4.9, 1.4.10 (both on mc 1.18.2)

### Latest Log

https://paste.ee/p/0rXDa

### Crash Report (if applicable)

https://paste.ee/p/OXTCi

### Steps to Reproduce

1. Start a world with the usual unreasonable quantity of mods
2. Add immersive portals once a forge port for 1.18.2 is released
3. Crash on entering the world

### What You Expected

Loading into the world and being able to make non-euclidean portals

### What Happened Instead

Crash on world load with an exception in the server tick loop.

Excerpt:

```
[11:58:54] [Server thread/ERROR] [minecraft/MinecraftServer]: Uncaught exception in server thread
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.m_129785_()" because the return value of "qouteall.q_misc_util.MiscHelper.getServer()" is null
	at qouteall.imm_ptl.core.portal.global_portals.GlobalPortalStorage.lambda$init$2(GlobalPortalStorage.java:65) ~[immersive-portals-1.4.10-mc1.18.2-forge.jar%23200!/:1.4.10] {re:classloading,re:mixin}
	at qouteall.q_misc_util.my_util.Signal.lambda$emit$0(Signal.java:18) ~[immersive-portals-1.4.10-mc1.18.2-forge.jar%23200!/:1.4.10] {re:mixin,re:classloading}
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?] {re:mixin}
	at qouteall.q_misc_util.my_util.Signal.emit(Signal.java:18) ~[immersive-portals-1.4.10-mc1.18.2-forge.jar%23200!/:1.4.10] {re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.handler$bep000$onServerClose(MinecraftServer.java:4462) ~[client-1.18.2-20220404.173914-srg.jar%23351!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:731) ~[client-1.18.2-20220404.173914-srg.jar%23351!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23351!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:?] {re:mixin}
```

### Additional Details

It's clearly an incompatibility, I just don't know what with so I can't open with them about it either. My guess would be Starlight and the major performance mods (Rubidium etc) or potentially mods altering chunk saving behavior like smooth chunks.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
Krypton is changing the network Protocol, that's a problem. If you don't need it, you can try dropping it. Otherwise you need to wait till I add compatibility.

**Comment by Nick1st** [comment]
What Krypton file are you using. Can you please get me a link?

**Comment by Shadowex3** [comment]
[This exact file](https://www.curseforge.com/minecraft/mc-mods/krypton-reforged/files/3819215). I got to easter egging Krypton literally right as you were updating this, if it didn't take a solid 10 minutes to load minecraft and save debugging would be so much less painful.

I could live without krypton unfortunately it looks like I also can't use Sodium (Rubidium on forge), Twilight Forest, or Create.

**Comment by Nick1st** [comment]
Rubidium should work, create is... Special. TF might deadlock a few chunks...

**Comment by Shadowex3** [comment]
Yeah that's the one I wound up dropping, it's still not finished anyway so there's not _that_ much content being lost. Create from what I can see the issue is flywheel's Fabric behavior, which may be fine on Forge since there's mods to fix compatibility between the element mods and flywheel.

Surprised that Krypton was the culprit.

**Comment by AprilCatStreams** [comment]
AbdElAziz333/Pluto#12 will resolve this once merged. Pluto is an alternative fork of Krypton ported to Forge, it's done by a mod author who I personally have had more experience with and trust more in porting. That's just my personal opinion and experience though. These mods both change the games code a lot though so your mileage in using both may very.

**Comment by border999** [comment]
any news on this issue? just updated to pluto-mc1.18.2-0.0.6 which was supposed to fix this but still crashing. I saw up above that you were saying Rubidium should be fine. 
[crash-2023-04-02_11.50.03-client.txt](https://github.com/iPortalTeam/ImmersivePortalsModForForge/files/11132702/crash-2023-04-02_11.50.03-client.txt)

**Comment by border999** [comment]
https://github.com/AbdElAziz333/Pluto/issues/23
