### ISSUE TITLE
My server crash when I open it with the Mod

### ISSUE THREAD

**Issue by Cpido** [iPortalTeam/ImmersivePortalsModForForge#6]
Hello I tried to put this mod into a Server and it crash, here the crash report: 
---- Minecraft Crash Report ----
// You're mean.

Time: 8/19/22, 12:20 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
        at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.2-40.1.73-universal.jar%2346!/:?] {re:classloading}
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.18.2-40.1.73-universal.jar%2346!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220404.173914-srg.jar%2341!/:?] {re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.1.73.jar%2317!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.18.2-40.1.73.jar%2317!/:1.0] {}
-- MOD imm_ptl_core --
Details:
        Caused by 0: java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER
                at qouteall.imm_ptl.core.platform_specific.forge.networking.IPMessage.register(IPMessage.java:37) ~[immersive-portals-1.4.9-mc1.18.2-forge.jar%2339!/:1.4.9] {re:classloading}
                at qouteall.imm_ptl.core.platform_specific.IPModEntry.commonSetup(IPModEntry.java:76) ~[immersive-portals-1.4.9-mc1.18.2-forge.jar%2339!/:1.4.9] {re:classloading}
                at net.minecraftforge.eventbus.ASMEventHandler_8_IPModEntry_commonSetup_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?] {}
                at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
                at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
                at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
                at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.1.73.jar%2343!/:?] {}
                at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.1.73.jar%2342!/:?] {}
                at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
                at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
                at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
                at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
                at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
                at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
                at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

        Mod File: /root/MinecraftServerForge/mods/immersive-portals-1.4.9-mc1.18.2-forge.jar
        Failure message: Immersive Portals Core (imm_ptl_core) encountered an error during the common_setup event phase
                java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER
        Mod Version: 1.4.9
        Mod Issue URL: https://github.com/Nick1st/SeeThroughPortals/issues
        Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER
Stacktrace:
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.18.2-40.1.73.jar%2317!/:1.0] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
        at qouteall.imm_ptl.core.platform_specific.forge.networking.IPMessage.register(IPMessage.java:37) ~[immersive-portals-1.4.9-mc1.18.2-forge.jar%2339!/:1.4.9] {re:classloading}
        at qouteall.imm_ptl.core.platform_specific.IPModEntry.commonSetup(IPModEntry.java:76) ~[immersive-portals-1.4.9-mc1.18.2-forge.jar%2339!/:1.4.9] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_8_IPModEntry_commonSetup_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.1.73.jar%2343!/:?] {}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.1.73.jar%2342!/:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
        Minecraft Version: 1.18.2
        Minecraft Version ID: 1.18.2
        Operating System: Linux (amd64) version 5.15.0-25-generic
        Java Version: 17.0.4, Private Build
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
        Memory: 1537112640 bytes (1465 MiB) / 2013265920 bytes (1920 MiB) up to 8589934592 bytes (8192 MiB)
        CPUs: 6
        Processor Vendor: AuthenticAMD
        Processor Name: AMD EPYC 7282 16-Core Processor
        Identifier: AuthenticAMD Family 23 Model 49 Stepping 0
        Microarchitecture: Zen 2
        Frequency (GHz): 2.00
        Number of physical packages: 1
        Number of physical CPUs: 6
        Number of logical CPUs: 6
        Graphics card #0 name: Device
        Graphics card #0 vendor: Vendor (0x1234)
        Graphics card #0 VRAM (MB): 16.00
        Graphics card #0 deviceId: 0x1111
        Graphics card #0 versionInfo: unknown
        Memory slot #0 capacity (MB): 16384.00
        Memory slot #0 clockSpeed (GHz): -0.00
        Memory slot #0 type: RAM
        Virtual memory max (MB): 8001.38
        Virtual memory used (MB): 2555.18
        Swap memory total (MB): 0.00
        Swap memory used (MB): 0.00
        JVM Flags: 1 total; -Xmx8G
        ModLauncher: 9.1.3+9.1.3+main.9b69c82a
        ModLauncher launch target: forgeserver
        ModLauncher naming: srg
        ModLauncher services:
                 mixin PLUGINSERVICE
                 eventbus PLUGINSERVICE
                 slf4jfixer PLUGINSERVICE
                 object_holder_definalize PLUGINSERVICE
                 runtime_enum_extender PLUGINSERVICE
                 capability_token_subclass PLUGINSERVICE
                 accesstransformer PLUGINSERVICE
                 runtimedistcleaner PLUGINSERVICE
                 mixin TRANSFORMATIONSERVICE
                 fml TRANSFORMATIONSERVICE
        FML Language Providers:
                minecraft@1.0
                lowcodefml@null
                javafml@null
        Mod List:
                server-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |SIDED_SETU|Manifest: NOSIGNATURE
                immersive-portals-1.4.9-mc1.18.2-forge.jar        |Immersive Portals             |immersive_portals             |1.4.9               |SIDED_SETU|Manifest: NOSIGNATURE
                forge-1.18.2-40.1.73-universal.jar                |Forge                         |forge                         |40.1.73             |SIDED_SETU|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
        Crash Report UUID: 22494b4c-1808-451c-85b8-c9d06504bca6
        FML: 40.1
        Forge: net.minecraftforge:40.1.73[12:20:41] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Immersive Portals Core (imm_ptl_core) encountered an error during the common_setup event phase
§7java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:222) ~[fmlcore-1.18.2-40.1.73.jar%2342!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:187) ~[fmlcore-1.18.2-40.1.73.jar%2342!/:?] {}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:187) ~[fmlcore-1.18.2-40.1.73.jar%2342!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$loadMods$14(ModLoader.java:170) ~[fmlcore-1.18.2-40.1.73.jar%2342!/:?] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:170) ~[fmlcore-1.18.2-40.1.73.jar%2342!/:?] {}
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:33) ~[forge-1.18.2-40.1.73-universal.jar%2346!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220404.173914-srg.jar%2341!/:?] {re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.1.73.jar%2317!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

**I'm sorry if it's something I haven't finished seeing or it's something obvious, I'm not very involved in these issues so I don't know what it could be, I'm sorry for bothering if that's the case 😅**

**Comment by Nick1st** [comment]
Please use the issue template to report bugs

**Comment by Cpido** [comment]
Oh ok, sorry for that I hadn't seen it, I don't use GitHub much so I'm a bit lost haha, when I have a free moment I'll post it for you, thanks for letting me know btw!
